### ISSUE TITLE
why long is used here?

### ISSUE THREAD

**Issue by 9868rishi** [suraj-996/lying-powder-9405#26]
https://github.com/suraj-996/lying-powder-9405/blob/3082b1ac778459a80a16678f221118581491b9df/Covid-19-VaccineScheduler/src/main/java/com/vs/model/VaccineRegistration.java#L19

**Comment by TruptiRG** [comment]
At the time of adding it didn't think about the format like "+" or "+91" before the number.
But got it and changed it to string as it seems correct in string.
