### ISSUE TITLE
what is the use of this controller if everything is commented

### ISSUE THREAD

**Issue by 9868rishi** [suraj-996/lying-powder-9405#27]
https://github.com/suraj-996/lying-powder-9405/blob/3082b1ac778459a80a16678f221118581491b9df/Covid-19-VaccineScheduler/src/main/java/com/vs/controller/VaccineRegistrationController.java#L25

**Comment by TruptiRG** [comment]
At first, added all the respective controllers, but later on, combined all into the Login controller, Admin controller, and the User controller.
